name: Publish to npm on Merge to Main

on:
  push:
    branches:
      - main

jobs:
  publish-npm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Ensure full history is available

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Bump Version & Create a new tag
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # Bump the version
          pnpm version patch
          
          # Set the remote URL with PAT token
          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git
          
          # Check the status and commit changes
          git status
          git add -A
          git commit -m "Bump version to $(pnpm pkg get version)" || echo "No changes to commit"
          
          # Push changes and tags
          git push origin main --tags
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Publish to npm
        run: pnpm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_SECRET_CODE_INSIGHT }}
